### ISSUE TITLE
Create a V3 zip with the chinese

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/msf-ebola#35]
La trad en chinois vient d'être réalisée.
Pourrais-tu releaser sur preprod et créer le zip de la V3 stp?

**Comment by annelisebouyer** [comment]
Alors ils viennent également d'ajouter le chinois simplifié comme langue.
Est-ce que tu pourrais steup releaser sur la preprod avec les modifs dans crowdin ?
Merci !

**Comment by Pirhoo** [comment]
Done.

**Comment by annelisebouyer** [comment]
Merci ! comment ça marche les urls dans ce cas là ?
Quand j'ouvre
http://development.msf-ebola.divshot.io/#!/?lang=zh-CN
et
http://development.msf-ebola.divshot.io/#!/?lang=zh-HK
j'ai exactement la meme version (HK)

**Comment by Pirhoo** [comment]
Eh, c'est sur deux caractères la langue. Et Crowdin me donne que *zh*.

**Comment by annelisebouyer** [comment]
Ah mince, normalement c'est sur 2 caractères oui mais pour le chinois crowdin me montre les codes comme ça zh-CN et zh-HK
mais c'est pas grave je peux lui dire de changer la langue via le menu
